---
- name: Stop Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Stop the VM
      azure_rm_virtualmachine:
        resource_group: myResourceGroup
        name: myVM
        state: true
        started: false
